
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author logonubc
 */
public class FormFuncionario extends javax.swing.JFrame {

  Funcionario funcionario = new Funcionario();
          
    
    public FormFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formfuncionario = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        setor = new javax.swing.JLabel();
        idade = new javax.swing.JLabel();
        btncadastrar = new javax.swing.JButton();
        btnexibir = new javax.swing.JButton();
        fieldnome = new javax.swing.JTextField();
        fieldtel = new javax.swing.JTextField();
        fieldsetor = new javax.swing.JTextField();
        fieldidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formfuncionario.setText("Formulário Funcionário");

        nome.setText("Nome");

        telefone.setText("Telefone");

        setor.setText("Setor");

        idade.setText("Idade");

        btncadastrar.setText("Cadastrar");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });

        btnexibir.setText("Exibir");
        btnexibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexibirActionPerformed(evt);
            }
        });

        fieldtel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldtelActionPerformed(evt);
            }
        });

        fieldsetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldsetorActionPerformed(evt);
            }
        });

        fieldidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldidadeActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar ao Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(telefone)
                            .addComponent(nome)
                            .addComponent(setor)
                            .addComponent(idade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldtel)
                                .addComponent(fieldsetor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(fieldidade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
                                    .addGap(69, 69, 69)))
                            .addComponent(fieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btncadastrar)
                        .addGap(49, 49, 49)
                        .addComponent(btnexibir)))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(formfuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formfuncionario)
                    .addComponent(jButton1))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(fieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefone)
                    .addComponent(fieldtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setor)
                    .addComponent(fieldsetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idade)
                    .addComponent(fieldidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncadastrar)
                    .addComponent(btnexibir))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldtelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldtelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldtelActionPerformed

    private void fieldsetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldsetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldsetorActionPerformed

    private void fieldidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldidadeActionPerformed

    private void btnexibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexibirActionPerformed
         this.fieldnome.setText(funcionario.nome);
         this.fieldidade.setText(" "+funcionario.idade);
         this.fieldtel.setText(" "+funcionario.telefone);
         this.fieldsetor.setText(" "+funcionario.setor);
    }//GEN-LAST:event_btnexibirActionPerformed

    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        String nome=this.fieldnome.getText();
         int telefone= Integer.parseInt(this.fieldtel.getText());
         int idade=Integer.parseInt(this.fieldidade.getText());
         String setor=this.fieldsetor.getText();
         funcionario.setor=setor;
         funcionario.telefone=telefone;
         funcionario.nome=nome;
         funcionario.idade=idade;
         JOptionPane.showMessageDialog(null,"Dados cadastrados com sucesso!");
         this.fieldsetor.setText(" ");
         this.fieldtel.setText(" ");
         this.fieldnome.setText(" ");
         this.fieldidade.setText(" ");
         
    }//GEN-LAST:event_btncadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new FormEscola().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadastrar;
    private javax.swing.JButton btnexibir;
    private javax.swing.JTextField fieldidade;
    private javax.swing.JTextField fieldnome;
    private javax.swing.JTextField fieldsetor;
    private javax.swing.JTextField fieldtel;
    private javax.swing.JLabel formfuncionario;
    private javax.swing.JLabel idade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel setor;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
