/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author logonubc
 */
public class FormEscola extends javax.swing.JFrame {

    /**
     * Creates new form FormEscola
     */
    public FormEscola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnaluno = new javax.swing.JButton();
        btnprofessor = new javax.swing.JButton();
        btnfuncionario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnaluno.setText("Aluno");
        btnaluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalunoActionPerformed(evt);
            }
        });

        btnprofessor.setText("Professor");
        btnprofessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofessorActionPerformed(evt);
            }
        });

        btnfuncionario.setText("Funcionário");
        btnfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfuncionarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Sistema Escolar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnaluno)
                        .addGap(38, 38, 38)
                        .addComponent(btnprofessor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnfuncionario)))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaluno)
                    .addComponent(btnprofessor))
                .addGap(37, 37, 37)
                .addComponent(btnfuncionario)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnalunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalunoActionPerformed
        new FormAluno().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnalunoActionPerformed

    private void btnprofessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofessorActionPerformed
        new FormProf().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnprofessorActionPerformed

    private void btnfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfuncionarioActionPerformed
        new FormFuncionario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnfuncionarioActionPerformed
    
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEscola().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaluno;
    private javax.swing.JButton btnfuncionario;
    private javax.swing.JButton btnprofessor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
